/**
 * HubSpot-defined association type IDs, keyed by the "from" object type ID used
 * by this node. Each entry is [associationTypeId, label].
 *
 * Used to build search filter options of the form `associations.0-{typeId}`,
 * which match records associated to another record via that association type.
 *
 * Source: https://developers.hubspot.com/docs/api-reference/latest/crm/associations/associate-records/guide
 * Only HubSpot-defined (default) associations are listed; user-defined labels
 * are not included. Object types without a documented association table
 * (e.g. Products, Contracts) are intentionally absent.
 */
export const ASSOCIATION_TYPES: Record<string, Array<[number, string]>> = {
	// Contacts (0-1)
	'0-1': [
		[449, 'Contact to contact'],
		[279, 'Contact to company'],
		[1, 'Contact to primary company'],
		[931, 'Billing contact to company'],
		[4, 'Contact to deal'],
		[15, 'Contact to ticket'],
		[193, 'Contact to call'],
		[197, 'Contact to email'],
		[199, 'Contact to meeting'],
		[201, 'Contact to note'],
		[203, 'Contact to task'],
		[82, 'Contact to communication'],
		[454, 'Contact to postal mail'],
		[587, 'Contact to cart'],
		[508, 'Contact to order'],
		[178, 'Contact to invoice'],
		[388, 'Contact to payment'],
		[470, 'Contact to payment link'],
		[296, 'Contact to subscription'],
		[907, 'Contact to appointment'],
		[861, 'Contact to course'],
		[883, 'Contact to listing'],
		[799, 'Contact to service'],
		[97, 'Contact to feedback submission'],
		[1243, 'Contact to project'],
		[609, 'Contact to lead'],
		[70, 'Contact to quote'],
		[703, 'Signer contact to quote'],
		[1227, 'Billing contact to quote'],
		[1375, 'Contact to marketing event'],
	],
	// Companies (0-2)
	'0-2': [
		[450, 'Company to company'],
		[14, 'Child to parent company'],
		[13, 'Parent to child company'],
		[280, 'Company to contact'],
		[2, 'Company to primary contact'],
		[930, 'Company to billing contact'],
		[342, 'Company to deal'],
		[6, 'Primary company to deal'],
		[340, 'Company to ticket'],
		[25, 'Primary company to ticket'],
		[181, 'Company to call'],
		[185, 'Company to email'],
		[611, 'Company to lead'],
		[187, 'Company to meeting'],
		[189, 'Company to note'],
		[191, 'Company to task'],
		[88, 'Company to communication'],
		[460, 'Company to postal mail'],
		[180, 'Company to invoice'],
		[935, 'Company to order'],
		[510, 'Primary company to order'],
		[390, 'Company to payment'],
		[472, 'Company to payment link'],
		[72, 'Company to quote'],
		[1335, 'Billing company to quote'],
		[298, 'Company to subscription'],
		[909, 'Company to appointment'],
		[939, 'Company to course'],
		[885, 'Company to listing'],
		[793, 'Company to service'],
		[929, 'Company to feedback submission'],
		[1237, 'Company to project'],
		[1387, 'Company to marketing event'],
	],
	// Deals (0-3)
	'0-3': [
		[451, 'Deal to deal'],
		[3, 'Deal to contact'],
		[341, 'Deal to company'],
		[5, 'Deal to primary company'],
		[27, 'Deal to ticket'],
		[205, 'Deal to call'],
		[1038, 'Deal to lead'],
		[583, 'Primary deal to lead'],
		[209, 'Deal to email'],
		[1357, 'Deal to goal'],
		[211, 'Deal to meeting'],
		[213, 'Deal to note'],
		[215, 'Deal to task'],
		[86, 'Deal to communication'],
		[458, 'Deal to postal mail'],
		[313, 'Deal to deal split'],
		[19, 'Deal to line item'],
		[1346, 'Deal to cart'],
		[176, 'Deal to invoice'],
		[511, 'Deal to order'],
		[392, 'Deal to payment'],
		[474, 'Deal to payment link'],
		[63, 'Deal to quote'],
		[300, 'Deal to subscription'],
		[945, 'Deal to appointment'],
		[863, 'Deal to course'],
		[887, 'Deal to listing'],
		[795, 'Deal to service'],
		[985, 'Deal to feedback submission'],
		[1239, 'Deal to project'],
		[1389, 'Deal to marketing event'],
	],
	// Tickets (0-5)
	'0-5': [
		[452, 'Ticket to ticket'],
		[16, 'Ticket to contact'],
		[339, 'Ticket to company'],
		[26, 'Ticket to primary company'],
		[28, 'Ticket to deal'],
		[219, 'Ticket to call'],
		[223, 'Ticket to email'],
		[225, 'Ticket to meeting'],
		[227, 'Ticket to note'],
		[229, 'Ticket to task'],
		[84, 'Ticket to communication'],
		[456, 'Ticket to postal mail'],
		[32, 'Ticket to thread'],
		[278, 'Ticket to conversation'],
		[526, 'Ticket to order'],
		[947, 'Ticket to appointment'],
		[941, 'Ticket to course'],
		[943, 'Ticket to listing'],
		[797, 'Ticket to service'],
		[1122, 'Ticket to subscription'],
		[1355, 'Ticket to payment'],
		[99, 'Ticket to feedback submission'],
		[1241, 'Ticket to project'],
	],
	// Line Items (0-8)
	'0-8': [
		[571, 'Line item to abandoned cart'],
		[591, 'Line item to cart'],
		[396, 'Line item to payment'],
		[20, 'Line item to deal'],
		[368, 'Line item to discount'],
		[410, 'Line item to invoice'],
		[514, 'Line item to order'],
		[759, 'Line item to payment link'],
		[1345, 'Line item to project'],
		[68, 'Line item to quote'],
		[302, 'Line item to subscription'],
		[565, 'Upcoming line item to subscription'],
	],
	// Quotes (0-14)
	'0-14': [
		[69, 'Quote to contact'],
		[1226, 'Quote to billing contact'],
		[71, 'Quote to company'],
		[1334, 'Quote to billing company'],
		[64, 'Quote to deal'],
		[67, 'Quote to line item'],
		[286, 'Quote to quote template'],
		[362, 'Quote to discount'],
		[364, 'Quote to fee'],
		[366, 'Quote to tax'],
		[217, 'Quote to task'],
		[702, 'Quote to signer contact'],
		[733, 'Quote to cart'],
		[408, 'Quote to invoice'],
		[731, 'Quote to order'],
		[398, 'Quote to payment'],
		[304, 'Quote to subscription'],
		[1172, 'Quote to feedback submission'],
	],
	// Communications (0-18)
	'0-18': [
		[81, 'Communication to contact'],
		[87, 'Communication to company'],
		[85, 'Communication to deal'],
		[83, 'Communication to ticket'],
		[603, 'Communication to lead'],
		[785, 'Communication to order'],
		[925, 'Communication to appointment'],
		[879, 'Communication to course'],
		[903, 'Communication to listing'],
		[847, 'Communication to service'],
		[1282, 'Communication to project'],
	],
	// Tasks (0-27)
	'0-27': [
		[204, 'Task to contact'],
		[192, 'Task to company'],
		[216, 'Task to deal'],
		[230, 'Task to ticket'],
		[647, 'Task to lead'],
		[218, 'Task to quote'],
		[727, 'Task to order'],
		[923, 'Task to appointment'],
		[877, 'Task to course'],
		[901, 'Task to listing'],
		[853, 'Task to service'],
		[1247, 'Task to project'],
		[262, 'Task to marketing event'],
	],
	// Notes (0-46)
	'0-46': [
		[202, 'Note to contact'],
		[190, 'Note to company'],
		[214, 'Note to deal'],
		[228, 'Note to ticket'],
		[855, 'Note to lead'],
		[765, 'Note to order'],
		[921, 'Note to appointment'],
		[875, 'Note to course'],
		[899, 'Note to listing'],
		[837, 'Note to service'],
		[1249, 'Note to project'],
		[260, 'Note to marketing event'],
	],
	// Meetings (0-47)
	'0-47': [
		[200, 'Meeting to contact'],
		[188, 'Meeting to company'],
		[212, 'Meeting to deal'],
		[226, 'Meeting to ticket'],
		[601, 'Meeting to lead'],
		[769, 'Meeting to order'],
		[919, 'Meeting to appointment'],
		[873, 'Meeting to course'],
		[897, 'Meeting to listing'],
		[839, 'Meeting to service'],
	],
	// Calls (0-48)
	'0-48': [
		[913, 'Call to appointment'],
		[182, 'Call to company'],
		[194, 'Call to contact'],
		[206, 'Call to deal'],
		[1156, 'Call to feedback submission'],
		[597, 'Call to lead'],
		[773, 'Call to order'],
		[867, 'Call to course'],
		[891, 'Call to listing'],
		[1258, 'Call to project'],
		[841, 'Call to service'],
		[220, 'Call to ticket'],
	],
	// Emails (0-49)
	'0-49': [
		[917, 'Email to appointment'],
		[186, 'Email to company'],
		[198, 'Email to contact'],
		[871, 'Email to course'],
		[210, 'Email to deal'],
		[777, 'Email to order'],
		[895, 'Email to listing'],
		[1260, 'Email to project'],
		[843, 'Email to service'],
		[224, 'Email to ticket'],
		[498, 'Email to marketing event'],
	],
	// Invoices (0-53)
	'0-53': [
		[177, 'Invoice to contact'],
		[179, 'Invoice to company'],
		[175, 'Invoice to deal'],
		[407, 'Invoice to quote'],
		[622, 'Invoice to subscription'],
		[815, 'Invoice to payment link'],
		[517, 'Invoice to order'],
		[986, 'Invoice to ticket'],
		[409, 'Invoice to line item'],
		[411, 'Invoice to discount'],
		[413, 'Invoice to fee'],
		[415, 'Invoice to tax'],
		[541, 'Invoice to payment'],
		[691, 'Invoice to payment schedule installment'],
		[679, 'Invoice to data sync state'],
		[1160, 'Invoice to feedback submission'],
	],
	// Subscriptions (0-69)
	'0-69': [
		[295, 'Subscription to contact'],
		[297, 'Subscription to company'],
		[299, 'Subscription to deal'],
		[1121, 'Subscription to ticket'],
		[623, 'Subscription to invoice'],
		[301, 'Subscription to line item'],
		[303, 'Subscription to quote'],
		[478, 'Subscription to payment link'],
		[515, 'Subscription to order'],
		[1174, 'Subscription to feedback submission'],
	],
	// Payments (0-101)
	'0-101': [
		[389, 'Payment to company'],
		[387, 'Payment to contact'],
		[391, 'Payment to deal'],
		[428, 'Payment to discount'],
		[1326, 'Payment to fee'],
		[1170, 'Payment to feedback submission'],
		[542, 'Payment to invoice'],
		[395, 'Payment to line item'],
		[524, 'Payment to order'],
		[476, 'Payment to payment link'],
		[397, 'Payment to quote'],
		[393, 'Payment to subscription'],
		[1354, 'Payment to ticket'],
	],
	// Orders (0-123)
	'0-123': [
		[772, 'Order to call'],
		[593, 'Order to cart'],
		[507, 'Order to contact'],
		[784, 'Order to communication'],
		[934, 'Order to company'],
		[509, 'Order to primary company'],
		[512, 'Order to deal'],
		[519, 'Order to discount'],
		[521, 'Order to discount code'],
		[776, 'Order to email'],
		[1168, 'Order to feedback submission'],
		[518, 'Order to invoice'],
		[513, 'Order to line item'],
		[768, 'Order to meeting'],
		[764, 'Order to note'],
		[523, 'Order to payment'],
		[789, 'Order to postal mail'],
		[730, 'Order to quote'],
		[516, 'Order to subscription'],
		[726, 'Order to task'],
		[525, 'Order to ticket'],
		[2538, 'Order to marketing event'],
	],
	// Carts (0-142)
	'0-142': [
		[586, 'Cart to contact'],
		[1347, 'Cart to deal'],
		[588, 'Cart to discount'],
		[590, 'Cart to line item'],
		[592, 'Cart to order'],
		[732, 'Cart to quote'],
		[728, 'Cart to task'],
		[594, 'Cart to ticket'],
		[1158, 'Cart to feedback submission'],
	],
	// Services (0-162)
	'0-162': [
		[798, 'Service to contact'],
		[792, 'Service to company'],
		[794, 'Service to deal'],
		[796, 'Service to ticket'],
		[840, 'Service to call'],
		[842, 'Service to email'],
		[838, 'Service to meeting'],
		[836, 'Service to note'],
		[852, 'Service to task'],
		[846, 'Service to communication'],
		[848, 'Service to postal mail'],
		[1245, 'Service to project'],
		[2782, 'Service to marketing event'],
	],
	// Leads (0-136)
	'0-136': [
		[608, 'Lead to contact'],
		[578, 'Lead to primary contact'],
		[610, 'Lead to company'],
		[580, 'Lead to primary company'],
		[1037, 'Lead to deal'],
		[582, 'Lead to primary deal'],
		[596, 'Lead to call'],
		[598, 'Lead to email'],
		[600, 'Lead to meeting'],
		[854, 'Lead to note'],
		[646, 'Lead to task'],
		[602, 'Lead to communication'],
		[1162, 'Lead to feedback submission'],
		[1391, 'Lead to marketing event'],
	],
	// Projects (0-970)
	'0-970': [
		[1324, 'Project to appointment'],
		[1257, 'Project to call'],
		[1281, 'Project to communication'],
		[1236, 'Project to company'],
		[1299, 'Project to primary company'],
		[1242, 'Project to contact'],
		[1261, 'Project to conversation session'],
		[1322, 'Project to course'],
		[1304, 'Project to data sync'],
		[1238, 'Project to deal'],
		[1259, 'Project to email'],
		[1252, 'Project to engagement'],
		[1320, 'Project to listing'],
		[1250, 'Project to marketing event'],
		[1255, 'Project to meeting event'],
		[1248, 'Project to note'],
		[1263, 'Project to postal mail'],
		[1254, 'Project to project'],
		[1244, 'Project to service'],
		[1246, 'Project to task'],
		[1240, 'Project to ticket'],
	],
};
