import { INodeProperties } from 'n8n-workflow';

export const contactDescription: INodeProperties[] = [
  // ── Contact operations ────────────────────────────────────────────────
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: {
        resource: ['contact'],
      },
    },
    options: [
      {
        name: 'Create',
        value: 'create',
        description: 'Create a new contact',
        action: 'Create a contact',
      },
      {
        name: 'Delete',
        value: 'delete',
        description: 'Delete a contact by ID',
        action: 'Delete a contact',
      },
      {
        name: 'Get',
        value: 'get',
        description: 'Retrieve a single contact by ID',
        action: 'Get a contact',
      },
      {
        name: 'Get Many',
        value: 'getMany',
        description: 'Retrieve a list of contacts',
        action: 'Get many contacts',
      },
      {
        name: 'Update',
        value: 'update',
        description: 'Update an existing contact',
        action: 'Update a contact',
      },
    ],
    default: 'getMany',
  },

  // ── Get Many options ──────────────────────────────────────────────────
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    default: false,
    description: 'Whether to return all results or only up to a given limit',
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['getMany'],
      },
    },
  },
  {
    displayName: 'Page Size',
    name: 'pageSize',
    type: 'number',
    typeOptions: { minValue: 1 },
    default: 10,
    description: 'Number of contacts to return per page',
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['getMany'],
      },
    },
  },
  {
    displayName: 'Fields to Return',
    name: 'fieldsFilterMode',
    type: 'options',
    options: [
      {
        name: 'All Fields',
        value: 'all',
        description: 'Return all fields from each result',
      },
      {
        name: 'All Fields Except',
        value: 'except',
        description: 'Return all fields except the specified ones from each result',
      },
      {
        name: 'Selected Fields',
        value: 'selected',
        description: 'Return only the specified fields from each result. Supports dot notation.',
      },
    ],
    default: 'all',
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['getMany'],
      },
    },
  },
  {
    displayName: 'Fields to Include',
    name: 'fieldsToInclude',
    type: 'string',
    default: '',
    placeholder: 'ID,firstName,phones.number',
    description: 'Comma-separated list of fields to include in each result. Supports dot notation for nested fields (e.g. phones.number).',
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['getMany'],
        fieldsFilterMode: ['selected'],
      },
    },
  },
  {
    displayName: 'Fields to Exclude',
    name: 'fieldsToExclude',
    type: 'string',
    default: '',
    placeholder: 'updateKey,sortBy',
    description: 'Comma-separated list of fields to exclude from each result',
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['getMany'],
        fieldsFilterMode: ['except'],
      },
    },
  },
  {
    displayName: 'Additional Options',
    name: 'additionalOptions',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['getMany'],
      },
    },
    options: [
      {
        displayName: 'ID',
        name: 'id',
        type: 'string',
        default: '',
        placeholder: '123 or 123,456,789',
        description: 'Filter by contact ID. Separate multiple IDs with commas.',
      },
      {
        displayName: 'Keyword',
        name: 'keyword',
        type: 'string',
        default: '',
        description: 'Filter contacts by keyword search',
      },
      {
        displayName: 'Start Index',
        name: 'startIndex',
        type: 'number',
        typeOptions: { minValue: 1 },
        default: 1,
        description: 'The index of the first record to return (1-based)',
      },
      {
        displayName: 'Updated After',
        name: 'updatedAfter',
        type: 'dateTime',
        default: '',
        description: 'Only return contacts updated after this date and time. Timezone is always UTC.',
      },
    ],
  },

  // ── Get / Update / Delete contact ID ──────────────────────────────────
  {
    displayName: 'Contact ID',
    name: 'contactId',
    type: 'string',
    default: '',
    required: true,
    description: 'The ID of the contact',
    displayOptions: {
      show: {
        resource: ['contact'],
        operation: ['get', 'update', 'delete'],
      },
    },
  },

  // ── Create contact fields ─────────────────────────────────────────────
  {
    displayName: 'Input Mode',
    name: 'inputMode',
    type: 'options',
    options: [
      { name: 'Custom JSON', value: 'json', description: 'Provide a raw JSON body' },
      { name: 'Fields', value: 'fields', description: 'Fill in individual fields' },
    ],
    default: 'fields',
    displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
  },
  {
    displayName: 'First Name',
    name: 'firstName',
    type: 'string',
    default: '',
    required: true,
    description: 'The first name of the contact',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'] } },
  },
  {
    displayName: 'Last Name',
    name: 'lastName',
    type: 'string',
    default: '',
    required: true,
    description: 'The last name of the contact',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'] } },
  },
  {
    displayName: 'Use Entity Address',
    name: 'useEntityAddress',
    type: 'boolean',
    default: false,
    required: true,
    description: 'Whether to use the associated entity\'s address instead of an address entered here',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'] } },
  },
  {
    displayName: 'Address Line 1',
    name: 'addressLine1',
    type: 'string',
    default: '',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'], useEntityAddress: [false] } },
  },
  {
    displayName: 'Address Line 2',
    name: 'addressLine2',
    type: 'string',
    default: '',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'], useEntityAddress: [false] } },
  },
  {
    displayName: 'City',
    name: 'city',
    type: 'string',
    default: '',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'], useEntityAddress: [false] } },
  },
  {
    displayName: 'State Code',
    name: 'state',
    type: 'string',
    default: '',
    placeholder: 'CO',
    // Not marked required: true here even though the API requires it whenever
    // Use Entity Address is off — that field can be expression-driven, and n8n
    // force-shows/force-requires fields whose show condition depends on an
    // expression-driven parameter regardless of its resolved value. Enforced
    // instead in execute() once the real value of useEntityAddress is known.
    description: '2-letter state code (e.g. CO, TX, CA). Required when "Use Entity Address" is false.',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'], useEntityAddress: [false] } },
  },
  {
    displayName: 'Postal Code',
    name: 'postalCode',
    type: 'string',
    default: '',
    description: 'ZIP / postal code',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'], useEntityAddress: [false] } },
  },
  {
    displayName: 'Entities',
    name: 'entities',
    type: 'string',
    default: '',
    placeholder: '123,456',
    description: 'Comma-separated list of entity IDs to associate with the contact',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'] } },
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['fields'] } },
    options: [
      { displayName: 'Classifications', name: 'classifications', type: 'string', default: '' },
      {
        displayName: 'Emails',
        name: 'emails',
        type: 'string',
        default: '',
        placeholder: 'jane@example.com,jdoe@example.com',
        description: 'Comma-separated list of email addresses',
      },
      { displayName: 'Inactive', name: 'inactive', type: 'boolean', default: false },
      { displayName: 'Keywords', name: 'keywords', type: 'string', default: '' },
      { displayName: 'Middle Name', name: 'middleName', type: 'string', default: '' },
      {
        displayName: 'Phones',
        name: 'phones',
        type: 'string',
        default: '',
        placeholder: '5551234567,5559876543',
        description: 'Comma-separated list of phone numbers',
      },
      { displayName: 'Salutation', name: 'salutation', type: 'string', default: '' },
      { displayName: 'Sort By', name: 'sortBy', type: 'string', default: '' },
      { displayName: 'Title', name: 'title', type: 'string', default: '' },
      { displayName: 'Web Enabled', name: 'webEnabled', type: 'boolean', default: false },
      { displayName: 'Website', name: 'website', type: 'string', default: '' },
    ],
  },
  {
    displayName: 'JSON Body',
    name: 'customJson',
    type: 'json',
    default: '{\n  "firstName": "string",\n  "middleName": "string",\n  "lastName": "string",\n  "salutation": "string",\n  "sortBy": "string",\n  "useEntityAddress": false,\n  "addressLine1": "string",\n  "addressLine2": "string",\n  "city": "string",\n  "state": "string",\n  "postalCode": "string",\n  "title": "string",\n  "website": "string.com",\n  "entities": [{"entityId": 123}],\n  "inactive": false,\n  "webEnabled": false,\n  "keywords": null,\n  "emails": [\n    {\n      "address": "string@email.com",\n      "type": "",\n      "preference": ""\n    }\n  ],\n  "phones": [\n    {\n      "number": "string",\n      "description": "",\n      "code": ""\n    }\n  ],\n  "classifications": null,\n  "id": "string"\n}',
    description: 'Raw JSON body to send to the API',
    displayOptions: { show: { resource: ['contact'], operation: ['create'], inputMode: ['json'] } },
  },

  // ── Update contact fields ──────────────────────────────────────────────
  {
    displayName: 'Input Mode',
    name: 'inputMode',
    type: 'options',
    options: [
      { name: 'Custom JSON', value: 'json', description: 'Provide a raw JSON patch (merged on top of existing data)' },
      { name: 'Fields', value: 'fields', description: 'Fill in individual fields' },
    ],
    default: 'fields',
    displayOptions: { show: { resource: ['contact'], operation: ['update'] } },
  },
  {
    displayName: 'Clear Fields',
    name: 'clearFields',
    type: 'multiOptions',
    default: [],
    description: 'Fields to explicitly clear. Arrays are set to [], all other fields to "".',
    displayOptions: { show: { resource: ['contact'], operation: ['update'], inputMode: ['fields'] } },
    options: [
      { name: 'Address Line 1', value: 'addressLine1' },
      { name: 'Address Line 2', value: 'addressLine2' },
      { name: 'City', value: 'city' },
      { name: 'Classifications', value: 'classifications' },
      { name: 'Emails', value: 'emails' },
      { name: 'Entities', value: 'entities' },
      { name: 'Keywords', value: 'keywords' },
      { name: 'Middle Name', value: 'middleName' },
      { name: 'Phones', value: 'phones' },
      { name: 'Postal Code', value: 'postalCode' },
      { name: 'Salutation', value: 'salutation' },
      { name: 'Sort By', value: 'sortBy' },
      { name: 'State', value: 'state' },
      { name: 'Title', value: 'title' },
      { name: 'Website', value: 'website' },
    ],
  },
  {
    displayName: 'Update Fields',
    name: 'updateFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    description: 'Fields to update on the contact. Only provided fields will be overwritten.',
    displayOptions: { show: { resource: ['contact'], operation: ['update'], inputMode: ['fields'] } },
    options: [
      { displayName: 'Address Line 1', name: 'addressLine1', type: 'string', default: '' },
      { displayName: 'Address Line 2', name: 'addressLine2', type: 'string', default: '' },
      { displayName: 'City', name: 'city', type: 'string', default: '' },
      { displayName: 'Classifications', name: 'classifications', type: 'string', default: '' },
      {
        displayName: 'Emails',
        name: 'emails',
        type: 'string',
        default: '',
        placeholder: 'jane@example.com,jdoe@example.com',
        description: 'Comma-separated list of email addresses. Replaces the existing emails if provided.',
      },
      {
        displayName: 'Entities',
        name: 'entities',
        type: 'string',
        default: '',
        placeholder: '123,456',
        description: 'Comma-separated list of entity IDs. Replaces the existing entities if provided.',
      },
      { displayName: 'First Name', name: 'firstName', type: 'string', default: '' },
      { displayName: 'Inactive', name: 'inactive', type: 'boolean', default: false },
      { displayName: 'Keywords', name: 'keywords', type: 'string', default: '' },
      { displayName: 'Last Name', name: 'lastName', type: 'string', default: '' },
      { displayName: 'Middle Name', name: 'middleName', type: 'string', default: '' },
      {
        displayName: 'Phones',
        name: 'phones',
        type: 'string',
        default: '',
        placeholder: '5551234567,5559876543',
        description: 'Comma-separated list of phone numbers. Replaces the existing phones if provided.',
      },
      { displayName: 'Postal Code', name: 'postalCode', type: 'string', default: '', description: 'ZIP / postal code' },
      { displayName: 'Salutation', name: 'salutation', type: 'string', default: '' },
      { displayName: 'Sort By', name: 'sortBy', type: 'string', default: '' },
      {
        displayName: 'State Code',
        name: 'state',
        type: 'string',
        default: '',
        placeholder: 'CO',
        description: '2-letter state code (e.g. CO, TX, CA)',
      },
      { displayName: 'Title', name: 'title', type: 'string', default: '' },
      { displayName: 'Use Entity Address', name: 'useEntityAddress', type: 'boolean', default: false },
      { displayName: 'Web Enabled', name: 'webEnabled', type: 'boolean', default: false },
      { displayName: 'Website', name: 'website', type: 'string', default: '' },
    ],
  },
  {
    displayName: 'JSON Patch',
    name: 'updateCustomJson',
    type: 'json',
    default: '{\n  "id": "string",\n  "firstName": "string",\n  "middleName": "string",\n  "lastName": "string",\n  "salutation": "string",\n  "sortBy": "string",\n  "useEntityAddress": false,\n  "addressLine1": "string",\n  "addressLine2": "string",\n  "city": "string",\n  "state": "string",\n  "postalCode": "string",\n  "title": "string",\n  "website": "string.com",\n  "entities": [{"entityId": 123}],\n  "inactive": false,\n  "webEnabled": false,\n  "keywords": null,\n  "emails": [\n    {\n      "address": "string@email.com",\n      "type": "",\n      "preference": ""\n    }\n  ],\n  "phones": [\n    {\n      "number": "string",\n      "description": "",\n      "code": ""\n    }\n  ],\n  "classifications": null\n}',
    description: 'Fields in this JSON are merged on top of the existing contact record',
    displayOptions: { show: { resource: ['contact'], operation: ['update'], inputMode: ['json'] } },
  },
];
