import { INodeProperties } from 'n8n-workflow';

export const customerDescription: INodeProperties[] = [
  // ── Customer operations ───────────────────────────────────────────────
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: {
        resource: ['customer'],
      },
    },
    options: [
      {
        name: 'Create',
        value: 'create',
        description: 'Create a new customer',
        action: 'Create a customer',
      },
      {
        name: 'Get',
        value: 'get',
        description: 'Retrieve a single customer by ID',
        action: 'Get a customer',
      },
      {
        name: 'Get Many',
        value: 'getMany',
        description: 'Retrieve a list of customers',
        action: 'Get many customers',
      },
      {
        name: 'Update',
        value: 'update',
        description: 'Update an existing customer',
        action: 'Update a customer',
      },
    ],
    default: 'getMany',
  },
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    default: false,
    description: 'Whether to return all results or only up to a given limit',
    displayOptions: {
      show: {
        resource: ['customer'],
        operation: ['getMany'],
      },
    },
  },
  {
    displayName: 'Page Size',
    name: 'pageSize',
    type: 'number',
    typeOptions: { minValue: 1 },
    default: 10,
    description: 'Number of customers to return per page',
    displayOptions: {
      show: {
        resource: ['customer'],
        operation: ['getMany'],
      },
    },
  },
  {
    displayName: 'Fields to Return',
    name: 'fieldsFilterMode',
    type: 'options',
    options: [
      {
        name: 'All Fields',
        value: 'all',
        description: 'Return all fields from each result',
      },
      {
        name: 'All Fields Except',
        value: 'except',
        description: 'Return all fields except the specified ones from each result',
      },
      {
        name: 'Selected Fields',
        value: 'selected',
        description: 'Return only the specified fields from each result. Supports dot notation.',
      },
    ],
    default: 'all',
    displayOptions: {
      show: {
        resource: ['customer'],
        operation: ['getMany'],
      },
    },
  },
  {
    displayName: 'Fields to Include',
    name: 'fieldsToInclude',
    type: 'string',
    default: '',
    placeholder: 'firstName,lastName,emails',
    description: 'Comma-separated list of fields to include in each result',
    displayOptions: {
      show: {
        resource: ['customer'],
        operation: ['getMany'],
        fieldsFilterMode: ['selected'],
      },
    },
  },
  {
    displayName: 'Fields to Exclude',
    name: 'fieldsToExclude',
    type: 'string',
    default: '',
    placeholder: 'updateKey,sortBy',
    description: 'Comma-separated list of fields to exclude from each result',
    displayOptions: {
      show: {
        resource: ['customer'],
        operation: ['getMany'],
        fieldsFilterMode: ['except'],
      },
    },
  },
  {
    displayName: 'Additional Options',
    name: 'additionalOptions',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        resource: ['customer'],
        operation: ['getMany'],
      },
    },
    options: [
      {
        displayName: 'ID',
        name: 'id',
        type: 'string',
        default: '',
        placeholder: '123 or 123,456,789',
        description: 'Filter by customer ID. Separate multiple IDs with commas.',
      },
      {
        displayName: 'Keyword',
        name: 'keyword',
        type: 'string',
        default: '',
        description: 'Filter customers by keyword search',
      },
      {
        displayName: 'Start Index',
        name: 'startIndex',
        type: 'number',
        typeOptions: { minValue: 1 },
        default: 1,
        description: 'The index of the first record to return (1-based)',
      },
      {
        displayName: 'Updated After',
        name: 'updatedAfter',
        type: 'dateTime',
        default: '',
        description: 'Only return customers updated after this date and time. Timezone is always UTC.',
      },
    ],
  },
  {
    displayName: 'Customer ID',
    name: 'customerId',
    type: 'string',
    default: '',
    required: true,
    description: 'The ID of the customer',
    displayOptions: {
      show: {
        resource: ['customer'],
        operation: ['get', 'update'],
      },
    },
  },

  // ── Create customer fields ────────────────────────────────────────────
  {
    displayName: 'Input Mode',
    name: 'inputMode',
    type: 'options',
    options: [
      { name: 'Custom JSON', value: 'json', description: 'Provide a raw JSON body' },
      { name: 'Fields', value: 'fields', description: 'Fill in individual fields' },
    ],
    default: 'fields',
    displayOptions: { show: { resource: ['customer'], operation: ['create'] } },
  },
  {
    displayName: 'Name',
    name: 'name',
    type: 'string',
    default: '',
    required: true,
    description: 'The name of the customer',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'] } },
  },
  {
    displayName: 'Is BillTo',
    name: 'isBillTo',
    type: 'boolean',
    default: true,
    required: true,
    description: 'Whether this customer is a bill-to customer',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'] } },
  },
  {
    displayName: 'Is ShipTo',
    name: 'isShipTo',
    type: 'boolean',
    default: true,
    required: true,
    description: 'Whether this customer is a ship-to customer',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'] } },
  },
  {
    displayName: 'Sort By',
    name: 'sortBy',
    type: 'string',
    default: '',
    required: true,
    description: 'Sort key for the customer. Maximum 12 characters.',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'] } },
  },
  {
    displayName: 'Name Index',
    name: 'nameIndex',
    type: 'string',
    default: '',
    required: true,
    description: 'Name index for the customer. Maximum 12 characters.',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'] } },
  },
  {
    displayName: 'BillTo ID',
    name: 'billToId',
    type: 'number',
    default: 0,
    required: true,
    description: 'The ID of the existing bill-to customer. Required when "Is BillTo" is false.',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'], isBillTo: [false] } },
  },
  {
    displayName: 'Types',
    name: 'types',
    type: 'fixedCollection',
    typeOptions: { multipleValues: true },
    placeholder: 'Add Type',
    default: {},
    description: 'Customer types (e.g. PROPANE, LVL-2)',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'] } },
    options: [
      {
        name: 'typeValues',
        displayName: 'Type',
        values: [{ displayName: 'Type', name: 'type', type: 'string', default: '', description: 'The customer type value (e.g. PROPANE)' }],
      },
    ],
  },
  {
    displayName: 'ShipTo List',
    name: 'shipToLists',
    type: 'fixedCollection',
    typeOptions: { multipleValues: true },
    placeholder: 'Add ShipTo',
    default: {},
    description: 'Associated ship-to customers',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'] } },
    options: [
      {
        name: 'shipToValues',
        displayName: 'ShipTo',
        values: [{ displayName: 'ShipTo ID', name: 'shipToId', type: 'number', default: 0 }],
      },
    ],
  },
  {
    displayName: 'Contacts',
    name: 'contacts',
    type: 'fixedCollection',
    typeOptions: { multipleValues: true },
    placeholder: 'Add Contact',
    default: {},
    description: 'Contacts to associate with the customer',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'] } },
    options: [
      {
        name: 'contactValues',
        displayName: 'Contact',
        values: [{ displayName: 'Contact ID', name: 'id', type: 'number', default: 0 }],
      },
    ],
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['fields'] } },
    options: [
      { displayName: 'Address Line 1', name: 'addressLine1', type: 'string', default: '' },
      { displayName: 'Address Line 2', name: 'addressLine2', type: 'string', default: '' },
      { displayName: 'City', name: 'city', type: 'string', default: '' },
      { displayName: 'Default PO Number', name: 'defaultPoNumber', type: 'string', default: '' },
      { displayName: 'Default Price Class', name: 'defaultPriceClass', type: 'string', default: '' },
      { displayName: 'Default Ship Via', name: 'defaultShipVia', type: 'string', default: '' },
      { displayName: 'Default Terms', name: 'defaultTerms', type: 'string', default: '' },
      { displayName: 'Freight In Exempt', name: 'freightInExempt', type: 'boolean', default: false },
      { displayName: 'Freight Out Exempt', name: 'freightOutExempt', type: 'boolean', default: false },
      { displayName: 'Home Branch', name: 'homeBranch', type: 'string', default: '' },
      { displayName: 'Home Territory', name: 'homeTerritory', type: 'string', default: '' },
      { displayName: 'Inside Salesperson', name: 'insideSalesperson', type: 'string', default: '' },
      { displayName: 'Outside Salesperson', name: 'outsideSalesperson', type: 'string', default: '' },
      { displayName: 'Postal Code', name: 'postalCode', type: 'string', default: '', description: 'ZIP / postal code' },
      {
        displayName: 'State Code',
        name: 'state',
        type: 'string',
        default: '',
        placeholder: 'CO',
        description: '2-letter state code (e.g. CO, TX, CA)',
      },
    ],
  },
  {
    displayName: 'JSON Body',
    name: 'customJson',
    type: 'json',
    default: '{\n  "name": "string",\n  "addressLine1": "string",\n  "addressLine2": "string",\n  "city": "string",\n  "state": "string",\n  "postalCode": "string",\n  "isBillTo": false,\n  "isShipTo": true,\n  "sortBy": "string",\n  "nameIndex": "string",\n  "billToId": 123,\n  "defaultPriceClass": "string",\n  "outsideSalesperson": "string",\n  "insideSalesperson": "string",\n  "defaultPoNumber": "string",\n  "defaultShipVia": "string",\n  "freightInExempt": false,\n  "freightOutExempt": false,\n  "defaultTerms": "string",\n  "homeBranch": "string",\n  "homeTerritory": "string",\n  "types": [{"type": "string"}],\n  "shipToLists": [{"shipToId": 0}],\n  "contacts": [{"id": 0}]\n}',
    description: 'Raw JSON body to send to the API',
    displayOptions: { show: { resource: ['customer'], operation: ['create'], inputMode: ['json'] } },
  },

  // ── Update customer fields ────────────────────────────────────────────
  {
    displayName: 'Input Mode',
    name: 'inputMode',
    type: 'options',
    options: [
      { name: 'Custom JSON', value: 'json', description: 'Provide a raw JSON patch (merged on top of existing data)' },
      { name: 'Fields', value: 'fields', description: 'Fill in individual fields' },
    ],
    default: 'fields',
    displayOptions: { show: { resource: ['customer'], operation: ['update'] } },
  },
  {
    displayName: 'Clear Fields',
    name: 'clearFields',
    type: 'multiOptions',
    default: [],
    description: 'Fields to explicitly clear. Arrays are set to [], all other fields to "".',
    displayOptions: { show: { resource: ['customer'], operation: ['update'], inputMode: ['fields'] } },
    options: [
      { name: 'Address Line 1', value: 'addressLine1' },
      { name: 'Address Line 2', value: 'addressLine2' },
      { name: 'BillTo ID', value: 'billToId' },
      { name: 'City', value: 'city' },
      { name: 'Contacts', value: 'contacts' },
      { name: 'Default PO Number', value: 'defaultPoNumber' },
      { name: 'Default Price Class', value: 'defaultPriceClass' },
      { name: 'Default Ship Via', value: 'defaultShipVia' },
      { name: 'Default Terms', value: 'defaultTerms' },
      { name: 'Home Branch', value: 'homeBranch' },
      { name: 'Home Territory', value: 'homeTerritory' },
      { name: 'Inside Salesperson', value: 'insideSalesperson' },
      { name: 'Outside Salesperson', value: 'outsideSalesperson' },
      { name: 'Postal Code', value: 'postalCode' },
      { name: 'ShipTo List', value: 'shipToLists' },
      { name: 'State', value: 'state' },
      { name: 'Types', value: 'types' },
    ],
  },
  {
    displayName: 'Update Fields',
    name: 'updateFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    description: 'Fields to update on the customer. Only provided fields will be overwritten.',
    displayOptions: { show: { resource: ['customer'], operation: ['update'], inputMode: ['fields'] } },
    options: [
      { displayName: 'Address Line 1', name: 'addressLine1', type: 'string', default: '' },
      { displayName: 'Address Line 2', name: 'addressLine2', type: 'string', default: '' },
      { displayName: 'BillTo ID', name: 'billToId', type: 'number', default: 0, description: 'Required when setting "Is BillTo" to false' },
      { displayName: 'City', name: 'city', type: 'string', default: '' },
      { displayName: 'Default PO Number', name: 'defaultPoNumber', type: 'string', default: '' },
      { displayName: 'Default Price Class', name: 'defaultPriceClass', type: 'string', default: '' },
      { displayName: 'Default Ship Via', name: 'defaultShipVia', type: 'string', default: '' },
      { displayName: 'Default Terms', name: 'defaultTerms', type: 'string', default: '' },
      { displayName: 'Freight In Exempt', name: 'freightInExempt', type: 'boolean', default: false },
      { displayName: 'Freight Out Exempt', name: 'freightOutExempt', type: 'boolean', default: false },
      { displayName: 'Home Branch', name: 'homeBranch', type: 'string', default: '' },
      { displayName: 'Home Territory', name: 'homeTerritory', type: 'string', default: '' },
      { displayName: 'Inside Salesperson', name: 'insideSalesperson', type: 'string', default: '' },
      { displayName: 'Is BillTo', name: 'isBillTo', type: 'boolean', default: true },
      { displayName: 'Is ShipTo', name: 'isShipTo', type: 'boolean', default: true },
      { displayName: 'Name', name: 'name', type: 'string', default: '' },
      { displayName: 'Name Index', name: 'nameIndex', type: 'string', default: '', description: 'Maximum 12 characters' },
      { displayName: 'Outside Salesperson', name: 'outsideSalesperson', type: 'string', default: '' },
      { displayName: 'Postal Code', name: 'postalCode', type: 'string', default: '' },
      { displayName: 'Sort By', name: 'sortBy', type: 'string', default: '', description: 'Maximum 12 characters' },
      {
        displayName: 'State Code',
        name: 'state',
        type: 'string',
        default: '',
        placeholder: 'CO',
        description: '2-letter state code (e.g. CO, TX, CA)',
      },
    ],
  },
  {
    displayName: 'Types',
    name: 'updateTypes',
    type: 'fixedCollection',
    typeOptions: { multipleValues: true },
    placeholder: 'Add Type',
    default: {},
    description: 'Replaces the existing customer types if any entries are provided',
    displayOptions: { show: { resource: ['customer'], operation: ['update'], inputMode: ['fields'] } },
    options: [
      {
        name: 'typeValues',
        displayName: 'Type',
        values: [{ displayName: 'Type', name: 'type', type: 'string', default: '', description: 'The customer type value (e.g. PROPANE)' }],
      },
    ],
  },
  {
    displayName: 'ShipTo List',
    name: 'updateShipToLists',
    type: 'fixedCollection',
    typeOptions: { multipleValues: true },
    placeholder: 'Add ShipTo',
    default: {},
    description: 'Replaces the existing ship-to list if any entries are provided',
    displayOptions: { show: { resource: ['customer'], operation: ['update'], inputMode: ['fields'] } },
    options: [
      {
        name: 'shipToValues',
        displayName: 'ShipTo',
        values: [{ displayName: 'ShipTo ID', name: 'shipToId', type: 'number', default: 0 }],
      },
    ],
  },
  {
    displayName: 'Contacts',
    name: 'updateContacts',
    type: 'fixedCollection',
    typeOptions: { multipleValues: true },
    placeholder: 'Add Contact',
    default: {},
    description: 'Replaces the existing contacts if any entries are provided',
    displayOptions: { show: { resource: ['customer'], operation: ['update'], inputMode: ['fields'] } },
    options: [
      {
        name: 'contactValues',
        displayName: 'Contact',
        values: [{ displayName: 'Contact ID', name: 'id', type: 'number', default: 0 }],
      },
    ],
  },
  {
    displayName: 'JSON Patch',
    name: 'updateCustomJson',
    type: 'json',
    default: '{\n  "updateKey": "string",\n  "id": "string",\n  "name": "string",\n  "addressLine1": "string",\n  "addressLine2": "string",\n  "city": "string",\n  "state": "string",\n  "postalCode": "string",\n  "isBillTo": false,\n  "isShipTo": true,\n  "sortBy": "string",\n  "nameIndex": "string",\n  "billToId": 123,\n  "defaultPriceClass": "string",\n  "outsideSalesperson": "string",\n  "insideSalesperson": "string",\n  "defaultPoNumber": "string",\n  "defaultShipVia": "string",\n  "freightInExempt": false,\n  "freightOutExempt": false,\n  "defaultTerms": "string",\n  "homeBranch": "string",\n  "homeTerritory": "string",\n  "types": [{"type": "string"}],\n  "shipToLists": [{"shipToId": 0}],\n  "contacts": [{"id": 0}]\n}',
    description: 'Fields in this JSON are merged on top of the existing customer record',
    displayOptions: { show: { resource: ['customer'], operation: ['update'], inputMode: ['json'] } },
  },
];
