import { INodeProperties } from 'n8n-workflow';

export const salesOrderDescription: INodeProperties[] = [
  // ── Sales Order operations ────────────────────────────────────────────
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: {
        resource: ['salesOrder'],
      },
    },
    options: [
      {
        name: 'Create',
        value: 'create',
        description: 'Create a new sales order',
        action: 'Create a sales order',
      },
      {
        name: 'Create Shipment',
        value: 'createShipment',
        description: 'Create a shipment for a sales order',
        action: 'Create a sales order shipment',
      },
      {
        name: 'Get',
        value: 'get',
        description: 'Retrieve a single sales order by ID',
        action: 'Get a sales order',
      },
      {
        name: 'Get Many',
        value: 'getMany',
        description: 'Retrieve a list of sales orders',
        action: 'Get many sales orders',
      },
      {
        name: 'Get Order Change Log',
        value: 'getOrderChangeLog',
        description: 'Retrieve the change log for a sales order',
        action: 'Get sales order change log',
      },
      {
        name: 'Update Internal Notes',
        value: 'updateInternalNotes',
        description: 'Update internal notes on a sales order',
        action: 'Update sales order internal notes',
      },
      {
        name: 'Update PO Number',
        value: 'updatePONumber',
        description: 'Update the PO number on a sales order',
        action: 'Update sales order PO number',
      },
      {
        name: 'Update Ship Date',
        value: 'updateShipDate',
        description: 'Update the ship date on a sales order',
        action: 'Update sales order ship date',
      },
      {
        name: 'Update Ship Via',
        value: 'updateShipVia',
        description: 'Update the ship via on a sales order',
        action: 'Update sales order ship via',
      },
      {
        name: 'Update Shipping Instructions',
        value: 'updateShippingInstructions',
        description: 'Update shipping instructions on a sales order',
        action: 'Update sales order shipping instructions',
      },
      {
        name: 'Update Status',
        value: 'updateStatus',
        description: 'Update the status of a sales order',
        action: 'Update sales order status',
      },
    ],
    default: 'getMany',
  },
  {
    displayName: 'Return All',
    name: 'returnAll',
    type: 'boolean',
    default: false,
    description: 'Whether to return all results or only up to a given limit',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getMany'],
      },
    },
  },
  {
    displayName: 'Page Size',
    name: 'pageSize',
    type: 'number',
    typeOptions: { minValue: 1 },
    default: 10,
    description: 'Number of sales orders to return per page',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getMany'],
      },
    },
  },
  {
    displayName: 'Fields to Return',
    name: 'fieldsFilterMode',
    type: 'options',
    options: [
      {
        name: 'All Fields',
        value: 'all',
        description: 'Return all fields from each result',
      },
      {
        name: 'All Fields Except',
        value: 'except',
        description: 'Return all fields except the specified ones from each result',
      },
      {
        name: 'Selected Fields',
        value: 'selected',
        description: 'Return only the specified fields from each result. Supports dot notation.',
      },
    ],
    default: 'all',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getMany'],
      },
    },
  },
  {
    displayName: 'Fields to Include',
    name: 'fieldsToInclude',
    type: 'string',
    default: '',
    placeholder: 'ID,billToCustomer,lines.lineItemProduct.productId',
    description: 'Comma-separated list of fields to include in each result. Supports dot notation for nested fields (e.g. lines.lineItemProduct.productId).',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getMany'],
        fieldsFilterMode: ['selected'],
      },
    },
  },
  {
    displayName: 'Fields to Exclude',
    name: 'fieldsToExclude',
    type: 'string',
    default: '',
    placeholder: 'updateKey,sortBy',
    description: 'Comma-separated list of fields to exclude from each result',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getMany'],
        fieldsFilterMode: ['except'],
      },
    },
  },
  {
    displayName: 'Date Filter Options',
    name: 'dateFilterOptions',
    type: 'collection',
    placeholder: 'Add Date Filter',
    default: {},
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getMany'],
      },
    },
    options: [
      {
        displayName: 'Last Modified Date End',
        name: 'lastModifiedDateAndTimeStampEnd',
        type: 'dateTime',
        default: '',
        description: 'Only return orders last modified on or before this date and time. Timezone is always UTC.',
      },
      {
        displayName: 'Last Modified Date Start',
        name: 'lastModifiedDateAndTimeStampStart',
        type: 'dateTime',
        default: '',
        description: 'Only return orders last modified on or after this date and time. Timezone is always UTC.',
      },
      {
        displayName: 'Order Date End',
        name: 'orderDateEnd',
        type: 'dateTime',
        default: '',
        description: 'Only return orders created on or before this date and time. Timezone is always UTC.',
      },
      {
        displayName: 'Order Date Start',
        name: 'orderDateStart',
        type: 'dateTime',
        default: '',
        description: 'Only return orders created on or after this date and time. Timezone is always UTC.',
      },
      {
        displayName: 'Ship Date',
        name: 'shipDate',
        type: 'string',
        default: '',
        placeholder: '123 or 123,456,789',
        description: 'Filter by ship date. Separate multiple values with commas.',
      },
      {
        displayName: 'Ship Date End',
        name: 'shipDateEnd',
        type: 'dateTime',
        default: '',
        description: 'Only return orders with a ship date on or before this date. Timezone is always UTC.',
      },
      {
        displayName: 'Ship Date Start',
        name: 'shipDateStart',
        type: 'dateTime',
        default: '',
        description: 'Only return orders with a ship date on or after this date. Timezone is always UTC.',
      },
    ],
  },
  {
    displayName: 'Additional Options',
    name: 'additionalOptions',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['getMany'],
      },
    },
    options: [
      {
        displayName: 'BillTo',
        name: 'billTo',
        type: 'string',
        default: '',
        placeholder: '123 or 123,456,789',
        description: 'Filter by bill-to ID. Separate multiple values with commas.',
      },
      {
        displayName: 'ID',
        name: 'id',
        type: 'string',
        default: '',
        placeholder: 'S2681000.0001 or S2681000.0001,S2681000.0002',
        description: 'Filter by sales order ID. Separate multiple IDs with commas.',
      },
      {
        displayName: 'Inside Salesperson',
        name: 'insideSalesperson',
        type: 'string',
        default: '',
        description: 'Filter by inside salesperson. Separate multiple values with commas.',
      },
      {
        displayName: 'Only IDs',
        name: 'onlyIds',
        type: 'boolean',
        default: false,
        description: 'Whether to return only order IDs instead of full records',
      },
      {
        displayName: 'Order Status',
        name: 'orderStatus',
        type: 'multiOptions',
        options: [
          { name: 'Bid', value: 'Bid' },
          { name: 'Call When Available', value: 'CallWhenAvailable' },
          { name: 'Call When Complete', value: 'CallWhenComplete' },
          { name: 'Call When Specified', value: 'CallWhenSpecified' },
          { name: 'Cancel', value: 'Cancel' },
          { name: 'Direct', value: 'Direct' },
          { name: 'Direct Through Stock', value: 'DirectThroughStock' },
          { name: 'Invoice', value: 'Invoice' },
          { name: 'Payment', value: 'Payment' },
          { name: 'Pick Up Now', value: 'PickUpNow' },
          { name: 'Reserve Inventory', value: 'ReserveInventory' },
          { name: 'Ship Item Complete', value: 'ShipItemComplete' },
          { name: 'Ship Ticket', value: 'ShipTicket' },
          { name: 'Ship When Available', value: 'ShipWhenAvailable' },
          { name: 'Ship When Complete', value: 'ShipWhenComplete' },
          { name: 'Ship When Specified', value: 'ShipWhenSpecified' },
        ],
        default: [],
        description: 'Filter by order status. Multiple statuses are allowed.',
      },
      {
        displayName: 'Outside Salesperson',
        name: 'outsideSalesperson',
        type: 'string',
        default: '',
        description: 'Filter by outside salesperson. Separate multiple values with commas.',
      },
      {
        displayName: 'Price Branch',
        name: 'priceBranch',
        type: 'string',
        default: '',
        placeholder: '123 or 123,456,789',
        description: 'Filter by price branch. Separate multiple values with commas.',
      },
      {
        displayName: 'Ship Branch',
        name: 'shipBranch',
        type: 'string',
        default: '',
        placeholder: '123 or 123,456,789',
        description: 'Filter by ship branch. Separate multiple values with commas.',
      },
      {
        displayName: 'Ship Via',
        name: 'shipVia',
        type: 'string',
        default: '',
        placeholder: '123 or 123,456,789',
        description: 'Filter by ship via. Separate multiple values with commas.',
      },
      {
        displayName: 'ShipTo',
        name: 'shipTo',
        type: 'string',
        default: '',
        placeholder: '123 or 123,456,789',
        description: 'Filter by ship-to ID. Separate multiple values with commas.',
      },
      {
        displayName: 'Sort',
        name: 'sort',
        type: 'options',
        options: [
          { name: 'Last Modified Date (Ascending)', value: '+LastModifiedDateAndTimeStamp' },
          { name: 'Last Modified Date (Descending)', value: '-LastModifiedDateAndTimeStamp' },
          { name: 'Order Date (Ascending)', value: '+orderDate' },
          { name: 'Order Date (Descending)', value: '-orderDate' },
          { name: 'Ship Date (Ascending)', value: '+shipDate' },
          { name: 'Ship Date (Descending)', value: '-shipDate' },
        ],
        default: '+orderDate',
        description: 'Sort order for results',
      },
      {
        displayName: 'Start Index',
        name: 'startIndex',
        type: 'number',
        typeOptions: { minValue: 1 },
        default: 1,
        description: 'The index of the first record to return (1-based)',
      },
      {
        displayName: 'Writer',
        name: 'writer',
        type: 'string',
        default: '',
        description: 'Filter by writer. Separate multiple values with commas.',
      },
    ],
  },
  {
    displayName: 'Sales Order ID',
    name: 'salesOrderId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'S2681000.0001',
    description: 'The ID of the sales order to retrieve',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['get'],
      },
    },
  },

  // ── Create Sales Order fields ─────────────────────────────────────────
  {
    displayName: 'Input Mode',
    name: 'salesOrderInputMode',
    type: 'options',
    options: [
      { name: 'Custom JSON', value: 'json', description: 'Provide a raw JSON body' },
      { name: 'Fields', value: 'fields', description: 'Fill in individual fields' },
    ],
    default: 'fields',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'] } },
  },
  {
    displayName: 'BillTo Customer ID',
    name: 'billToCustomerId',
    type: 'string',
    default: '',
    required: true,
    description: 'The ID of the bill-to customer',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'ShipTo Customer ID',
    name: 'shipToCustomerId',
    type: 'string',
    default: '',
    required: true,
    description: 'The ID of the ship-to customer',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'Price Branch',
    name: 'salesOrderPriceBranch',
    type: 'string',
    default: '',
    required: true,
    placeholder: '1',
    description: 'Home Branch of the Bill To Customer',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'Ship Branch',
    name: 'salesOrderShipBranch',
    type: 'string',
    default: '',
    required: true,
    placeholder: '1',
    description: 'Home Branch of the Bill To Customer',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'Order Status',
    name: 'salesOrderStatus',
    type: 'options',
    required: true,
    options: [
      { name: 'Bid', value: 'Bid' },
      { name: 'Call When Available', value: 'CallWhenAvailable' },
      { name: 'Call When Complete', value: 'CallWhenComplete' },
      { name: 'Call When Specified', value: 'CallWhenSpecified' },
      { name: 'Direct', value: 'Direct' },
      { name: 'Pick Up Now', value: 'PickUpNow' },
      { name: 'Ship Item Complete', value: 'ShipItemComplete' },
      { name: 'Ship Ticket', value: 'ShipTicket' },
      { name: 'Ship When Available', value: 'ShipWhenAvailable' },
      { name: 'Ship When Complete', value: 'ShipWhenComplete' },
      { name: 'Ship When Specified', value: 'ShipWhenSpecified' },
    ],
    default: 'Bid',
    description: 'The status of the sales order',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'Ship Date',
    name: 'salesOrderShipDate',
    type: 'string',
    default: '',
    required: true,
    placeholder: '2026-07-20',
    description: 'The ship date in ISO format (YYYY-MM-DD)',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'Required Date',
    name: 'salesOrderRequiredDate',
    type: 'string',
    default: '',
    required: true,
    placeholder: '2026-07-25',
    description: 'The required date in ISO format (YYYY-MM-DD)',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'Writer',
    name: 'salesOrderWriter',
    type: 'string',
    default: '',
    required: true,
    description: 'The writer code for the sales order',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'Fetch ShipTo\'s Address',
    name: 'salesOrderFetchShipAddress',
    type: 'boolean',
    default: true,
    description: 'Whether to automatically fetch address fields (street, city, state, etc.) from the ShipTo Customer record',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'Street 1',
    name: 'salesOrderStreet1',
    type: 'string',
    default: '',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'], salesOrderFetchShipAddress: [false] } },
  },
  {
    displayName: 'Street 2',
    name: 'salesOrderStreet2',
    type: 'string',
    default: '',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'], salesOrderFetchShipAddress: [false] } },
  },
  {
    displayName: 'City',
    name: 'salesOrderCity',
    type: 'string',
    default: '',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'], salesOrderFetchShipAddress: [false] } },
  },
  {
    displayName: 'State',
    name: 'salesOrderState',
    type: 'string',
    default: '',
    placeholder: 'CO',
    description: '2-letter state code',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'], salesOrderFetchShipAddress: [false] } },
  },
  {
    displayName: 'Postal Code',
    name: 'salesOrderPostalCode',
    type: 'string',
    default: '',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'], salesOrderFetchShipAddress: [false] } },
  },
  {
    displayName: 'Country',
    name: 'salesOrderCountry',
    type: 'string',
    default: '',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'], salesOrderFetchShipAddress: [false] } },
  },
  {
    displayName: 'Additional Options',
    name: 'salesOrderCreateOptions',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
    options: [
      {
        displayName: 'Customer PO Number',
        name: 'customerPONumber',
        type: 'string',
        default: '',
        description: 'Default PO Number of the BillTo Customer',
      },
      {
        displayName: 'Customer Release Number',
        name: 'customerReleaseNumber',
        type: 'string',
        default: '',
        description: 'Default Release Number of the BillTo Customer',
      },
      {
        displayName: 'Email',
        name: 'email',
        type: 'string',
        placeholder: 'name@email.com',
        default: '',
      },
      {
        displayName: 'Inside Salesperson',
        name: 'insideSalesPerson',
        type: 'string',
        default: '',
      },
      {
        displayName: 'Internal Notes',
        name: 'internalNotes',
        type: 'string',
        typeOptions: { rows: 3 },
        default: '',
      },
      {
        displayName: 'Outside Salesperson',
        name: 'outsideSalesPerson',
        type: 'string',
        default: '',
      },
      {
        displayName: 'Sales Source',
        name: 'salesSource',
        type: 'string',
        default: '',
        description: 'Sales Source Override of the BillTo Customer. Defaults to "Default Sales" if not provided.',
      },
      {
        displayName: 'Ship Via',
        name: 'shipVia',
        type: 'string',
        default: '',
        description: 'Default Ship Via of the BillTo Customer',
      },
      {
        displayName: 'Shipping Instructions',
        name: 'shippingInstructions',
        type: 'string',
        typeOptions: { rows: 3 },
        default: '',
      },
      {
        displayName: 'Terms Code',
        name: 'termsCode',
        type: 'string',
        default: '',
        description: 'Default Terms of the BillTo Customer',
      },
    ],
  },
  {
    displayName: 'Lines (JSON)',
    name: 'salesOrderLines',
    type: 'json',
    default: '[\n  {\n    "lineItemProduct": {\n      "productId": 246,\n      "quantity": 3,\n      "um": "ea",\n      "umQuantity": 1,\n      "unitPrice": 9.99,\n      "comments": ""\n    }\n  },\n  {\n    "lineItemProduct": {\n      "productId": 247,\n      "quantity": 3,\n      "um": "ea",\n      "umQuantity": 1\n    }\n  }\n]',
    description: 'Array of line items to add to the sales order',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['fields'] } },
  },
  {
    displayName: 'JSON Body',
    name: 'salesOrderCustomJson',
    type: 'json',
    default: '{\n  "priceBranch": 1,\n  "shipBranch": 1,\n  "billToCustomer": "12345",\n  "shipToCustomer": "12346",\n  "orderStatus": "Bid",\n  "salesSource": "Default Sales",\n  "shipDate": "2026-07-20",\n  "requiredDate": "2026-07-25",\n  "customerPONumber": "",\n  "customerReleaseNumber": "",\n  "shipVia": "",\n  "insideSalesPerson": "",\n  "outsideSalesPerson": "",\n  "writer": "",\n  "email": "",\n  "street1": "",\n  "street2": "",\n  "city": "",\n  "state": "",\n  "postalCode": "",\n  "country": "",\n  "internalNotes": "",\n  "shippingInstructions": "",\n  "termsCode": "",\n  "shipIds": ["12346"],\n  "lines": [\n    {\n      "lineItemProduct": {\n        "productId": 246,\n        "quantity": 3,\n        "um": "ea",\n        "umQuantity": 1,\n        "unitPrice": 9.99,\n        "comments": ""\n      }\n    },\n    {\n      "lineItemProduct": {\n        "productId": 247,\n        "quantity": 3,\n        "um": "ea",\n        "umQuantity": 1\n      }\n    }\n  ]\n}',
    description: 'Raw JSON body to send to the API',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['create'], salesOrderInputMode: ['json'] } },
  },

  // ── Create Shipment fields ─────────────────────────────────────────────
  {
    displayName: 'Sales Order ID',
    name: 'shipmentSalesOrderId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'S2688598',
    description: 'The ID of the sales order, without the generation',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['createShipment'],
      },
    },
  },
  {
    displayName: 'Source Generation ID',
    name: 'generationId',
    type: 'string',
    default: '',
    required: true,
    placeholder: '1',
    description: 'The generation ID that the new generation will be based on',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['createShipment'],
      },
    },
  },
  {
    displayName: 'Required Date',
    name: 'requiredDate',
    type: 'string',
    default: '',
    required: true,
    placeholder: '2026-07-25',
    description: 'The required date in ISO format (YYYY-MM-DD)',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['createShipment'],
      },
    },
  },
  {
    displayName: 'Ship Date',
    name: 'shipmentShipDate',
    type: 'string',
    default: '',
    required: true,
    placeholder: '2026-07-20',
    description: 'The ship date in ISO format (YYYY-MM-DD)',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['createShipment'],
      },
    },
  },
  {
    displayName: 'Ship Branch',
    name: 'shipBranch',
    type: 'string',
    default: '',
    required: true,
    placeholder: '1',
    description: 'The branch number from which the order ships',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['createShipment'],
      },
    },
  },
  {
    displayName: 'Ship Status',
    name: 'shipStatus',
    type: 'options',
    required: true,
    options: [
      { name: 'Bid', value: 'Bid' },
      { name: 'Call When Available', value: 'CallWhenAvailable' },
      { name: 'Call When Complete', value: 'CallWhenComplete' },
      { name: 'Call When Specified', value: 'CallWhenSpecified' },
      { name: 'Direct', value: 'Direct' },
      { name: 'Pick Up Now', value: 'PickUpNow' },
      { name: 'Ship Item Complete', value: 'ShipItemComplete' },
      { name: 'Ship Ticket', value: 'ShipTicket' },
      { name: 'Ship When Available', value: 'ShipWhenAvailable' },
      { name: 'Ship When Complete', value: 'ShipWhenComplete' },
      { name: 'Ship When Specified', value: 'ShipWhenSpecified' },
    ],
    default: 'Bid',
    description: 'The ship status for the shipment',
    displayOptions: {
      show: {
        resource: ['salesOrder'],
        operation: ['createShipment'],
      },
    },
  },

  // ── Get Order Change Log fields ───────────────────────────────────────
  {
    displayName: 'Sales Order ID',
    name: 'changeLogOrderId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'S2690635',
    description: 'The ID of the sales order, without the generation suffix',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['getOrderChangeLog'] } },
  },
  {
    displayName: 'Generation ID',
    name: 'changeLogGenerationId',
    type: 'string',
    default: '',
    placeholder: '1',
    description: 'Filter the change log to a specific generation. Leave blank to return all generations.',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['getOrderChangeLog'] } },
  },

  // ── Update Status fields ──────────────────────────────────────────────
  {
    displayName: 'Sales Order ID',
    name: 'statusOrderId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'S2680001.0001',
    description: 'The full sales order ID including generation suffix',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateStatus'] } },
  },
  {
    displayName: 'Order Status',
    name: 'statusOrderStatus',
    type: 'options',
    required: true,
    options: [
      { name: 'Bid', value: 'Bid' },
      { name: 'Call When Available', value: 'CallWhenAvailable' },
      { name: 'Call When Complete', value: 'CallWhenComplete' },
      { name: 'Call When Specified', value: 'CallWhenSpecified' },
      { name: 'Direct', value: 'Direct' },
      { name: 'Pick Up Now', value: 'PickUpNow' },
      { name: 'Ship Item Complete', value: 'ShipItemComplete' },
      { name: 'Ship Ticket', value: 'ShipTicket' },
      { name: 'Ship When Available', value: 'ShipWhenAvailable' },
      { name: 'Ship When Complete', value: 'ShipWhenComplete' },
      { name: 'Ship When Specified', value: 'ShipWhenSpecified' },
    ],
    default: 'Bid',
    description: 'The new status for the sales order',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateStatus'] } },
  },
  {
    displayName: 'Ship Date',
    name: 'statusShipDate',
    type: 'string',
    default: '',
    required: true,
    placeholder: '2026-07-20',
    description: 'The ship date in ISO format (YYYY-MM-DD). Required when Order Status is "Ship When Specified".',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateStatus'], statusOrderStatus: ['ShipWhenSpecified'] } },
  },

  // ── Update Shipping Instructions fields ───────────────────────────────
  {
    displayName: 'Sales Order ID',
    name: 'shippingInstructionsOrderId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'S2690635.0001',
    description: 'The full ID of the sales order including generation suffix',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateShippingInstructions'] } },
  },
  {
    displayName: 'Shipping Instructions',
    name: 'shippingInstructionsValue',
    type: 'string',
    typeOptions: { rows: 3 },
    default: '',
    required: true,
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateShippingInstructions'] } },
  },

  // ── Update PO Number fields ───────────────────────────────────────────
  {
    displayName: 'Sales Order ID',
    name: 'poNumberOrderId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'S2690635.0001',
    description: 'The full ID of the sales order including generation suffix',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updatePONumber'] } },
  },
  {
    displayName: 'PO Number',
    name: 'poNumberValue',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updatePONumber'] } },
  },

  // ── Update Ship Via fields ────────────────────────────────────────────
  {
    displayName: 'Sales Order ID',
    name: 'shipViaUpdateOrderId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'S2690635.0001',
    description: 'The full ID of the sales order including generation suffix',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateShipVia'] } },
  },
  {
    displayName: 'Ship Via',
    name: 'shipViaUpdateValue',
    type: 'string',
    default: '',
    required: true,
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateShipVia'] } },
  },

  // ── Update Ship Date fields ───────────────────────────────────────────
  {
    displayName: 'Sales Order ID',
    name: 'shipDateUpdateOrderId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'S2690635.0001',
    description: 'The full ID of the sales order including generation suffix',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateShipDate'] } },
  },
  {
    displayName: 'Ship Date',
    name: 'shipDateUpdateValue',
    type: 'string',
    default: '',
    required: true,
    placeholder: '2026-07-20',
    description: 'The new ship date in ISO format (YYYY-MM-DD)',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateShipDate'] } },
  },

  // ── Update Internal Notes fields ──────────────────────────────────────
  {
    displayName: 'Sales Order ID',
    name: 'internalNotesOrderId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'S2680001.0001',
    description: 'The full sales order ID including generation suffix',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateInternalNotes'] } },
  },
  {
    displayName: 'Internal Notes',
    name: 'internalNotesValue',
    type: 'string',
    typeOptions: { rows: 4 },
    default: '',
    required: true,
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateInternalNotes'] } },
  },
  {
    displayName: 'Copy To All Generations',
    name: 'copyToAll',
    type: 'boolean',
    default: false,
    description: 'Whether to apply the update to all generations of the order',
    displayOptions: { show: { resource: ['salesOrder'], operation: ['updateInternalNotes'] } },
  },
];
